import type { Metadata } from "next";
import "./globals.css";
import LeftSideComponent from "@/app/(private)/(components)/left-side/Left-Side-Component";

import PopularMoviesComponent from "@/app/(private)/(components)/appearances/popularMoviesComponent";
import WhatsNewComponent from "@/app/(private)/(components)/appearances/whatsNewComponent";
import TopRatedMoviesComponent from "@/app/(private)/(components)/appearances/topRatedMoviesComponent";
import React from "react";
import HeaderComponent from "@/app/(private)/(components)/header/headerComponent";
import ContextProvider from "@/app/(private)/context/contextProvider";


export const metadata: Metadata = {
  title: "Movie portal",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>)
{

    return (
    <html lang="en">
      <body>
      <div className="container">
          <LeftSideComponent/>
          <div className={"content-container"}>
              <ContextProvider>
                        <HeaderComponent/>
                  <hr/>
                  <div className="main-content-container">
                      <div className={"content-container-01"}>

                          {children}
                      </div>
                      <div className={"right-sidebar"}>
                          <WhatsNewComponent/>
                          <hr/>
                          <TopRatedMoviesComponent/>
                      </div>
                  </div>
              </ContextProvider>
          </div>
      </div>

      </body>
    </html>
    );
}
