import type { Metadata } from "next";
import "./globals.css";

import WhatsNewComponent from "@/app/(private)/(components)/appearances/whatsNewComponent";
import TopRatedMoviesComponent from "@/app/(private)/(components)/appearances/topRatedMoviesComponent";
import React from "react";
import HeaderComponent from "@/app/(private)/(components)/header/headerComponent";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';


export const metadata: Metadata = {
  title: "Movie portal",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>)
{

    return (
    <html lang="en">
    <body>
    <div className="container">
        <AppRouterCacheProvider>
        {/*<LeftSideComponent/>*/}
        <div className={"content-container"}>

            <HeaderComponent/>
                  <hr/>
                  <div className="main-content-container">
                      <div className={"content-container-01"}>
                                {children}
                      </div>
                      <div className={"right-sidebar"}>
                          <WhatsNewComponent/>
                          <hr/>
                          <TopRatedMoviesComponent/>
                      </div>
                  </div>
          </div>
        </AppRouterCacheProvider>
      </div>

      </body>
    </html>
    );
}
