import type { Metadata } from "next";
import "./globals.css";
import LeftSideComponent from "@/app/(private)/components/left-side/Left-Side-Component";
import MainContainer from "@/app/(private)/components/main-container/Main-Container";


export const metadata: Metadata = {
  title: "Movie portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="main-page">
          <LeftSideComponent/>
          <MainContainer/>
          {children}
      </div>

      </body>
    </html>
  );
}
